const GREYSCALE = {
  1: require("./Anti-Mage.jpeg"),
  2: require("./Axe.jpeg"),
  3: require("./Bane.jpeg"),
  4: require("./Bloodseeker.jpeg"),
  5: require("./Crystal_Maiden.jpeg"),
  6: require("./Drow_Ranger.jpeg"),
  7: require("./Earthshaker.jpeg"),
  8: require("./Juggernaut.jpeg"),
  9: require("./Mirana.jpeg"),
  10: require("./Morphling.jpeg"),
  11: require("./Shadow_Fiend.jpeg"),
  12: require("./Phantom_Lancer.jpeg"),
  13: require("./Puck.jpeg"),
  14: require("./Pudge.jpeg"),
  15: require("./Razor.jpeg"),
  16: require("./Sand_King.jpeg"),
  17: require("./Storm_Spirit.jpeg"),
  18: require("./Sven.jpeg"),
  19: require("./Tiny.jpeg"),
  20: require("./Vengeful_Spirit.jpeg"),
  21: require("./Windranger.jpeg"),
  22: require("./Zeus.jpeg"),
  23: require("./Kunkka.jpeg"),
  //   24: require("./.jpeg"),
  25: require("./Lina.jpeg"),
  26: require("./Lion.jpeg"),
  27: require("./Shadow_Shaman.jpeg"),
  28: require("./Slardar.jpeg"),
  29: require("./Tidehunter.jpeg"),
  30: require("./Witch_Doctor.jpeg"),
  31: require("./Lich.jpeg"),
  32: require("./Riki.jpeg"),
  33: require("./Enigma.jpeg"),
  34: require("./Tinker.jpeg"),
  35: require("./Sniper.jpeg"),
  36: require("./Necrophos.jpeg"),
  37: require("./Warlock.jpeg"),
  38: require("./Beastmaster.jpeg"),
  39: require("./Queen_of_Pain.jpeg"),
  40: require("./Venomancer.jpeg"),
  41: require("./Faceless_Void.jpeg"),
  42: require("./Wraith_King.jpeg"),
  43: require("./Death_Prophet.jpeg"),
  44: require("./Phantom_Assassin.jpeg"),
  45: require("./Pugna.jpeg"),
  46: require("./Templar_Assassin.jpeg"),
  47: require("./Viper.jpeg"),
  48: require("./Luna.jpeg"),
  49: require("./Dragon_Knight.jpeg"),
  50: require("./Dazzle.jpeg"),
  51: require("./Clockwerk.jpeg"),
  52: require("./Leshrac.jpeg"),
  53: require("./Natures_Prophet.jpeg"),
  54: require("./Lifestealer.jpeg"),
  55: require("./Dark_Seer.jpeg"),
  56: require("./Clinkz.jpeg"),
  57: require("./Omniknight.jpeg"),
  58: require("./Enchantress.jpeg"),
  59: require("./Huskar.jpeg"),
  60: require("./Night_Stalker.jpeg"),
  61: require("./Broodmother.jpeg"),
  62: require("./Bounty_Hunter.jpeg"),
  63: require("./Weaver.jpeg"),
  64: require("./Jakiro.jpeg"),
  65: require("./Batrider.jpeg"),
  66: require("./Chen.jpeg"),
  67: require("./Spectre.jpeg"),
  68: require("./Ancient_Apparition.jpeg"),
  69: require("./Doom.jpeg"),
  70: require("./Ursa.jpeg"),
  71: require("./Spirit_Breaker.jpeg"),
  72: require("./Gyrocopter.jpeg"),
  73: require("./Alchemist.jpeg"),
  74: require("./Invoker.jpeg"),
  75: require("./Silencer.jpeg"),
  76: require("./Outworld_Destroyer.jpeg"),
  77: require("./Lycan.jpeg"),
  78: require("./Brewmaster.jpeg"),
  79: require("./Shadow_Demon.jpeg"),
  80: require("./Lone_Druid.jpeg"),
  81: require("./Chaos_Knight.jpeg"),
  82: require("./Meepo.jpeg"),
  83: require("./Treant_Protector.jpeg"),
  84: require("./Ogre_Magi.jpeg"),
  85: require("./Undying.jpeg"),
  86: require("./Rubick.jpeg"),
  87: require("./Disruptor.jpeg"),
  88: require("./Nyx_Assassin.jpeg"),
  89: require("./Naga_Siren.jpeg"),
  90: require("./Keeper_of_the_Light.jpeg"),
  91: require("./Io.jpeg"),
  92: require("./Visage.jpeg"),
  93: require("./Slark.jpeg"),
  94: require("./Medusa.jpeg"),
  95: require("./Troll_Warlord.jpeg"),
  96: require("./Centaur_Warrunner.jpeg"),
  97: require("./Magnus.jpeg"),
  98: require("./Timbersaw.jpeg"),
  99: require("./Bristleback.jpeg"),
  100: require("./Tusk.jpeg"),
  101: require("./Skywrath_Mage.jpeg"),
  102: require("./Abaddon.jpeg"),
  103: require("./Elder_Titan.jpeg"),
  104: require("./Legion_Commander.jpeg"),
  105: require("./Techies.jpeg"),
  106: require("./Ember_Spirit.jpeg"),
  107: require("./Earth_Spirit.jpeg"),
  108: require("./Underlord.jpeg"),
  109: require("./Terrorblade.jpeg"),
  110: require("./Phoenix.jpeg"),
  111: require("./Oracle.jpeg"),
  112: require("./Winter_Wyvern.jpeg"),
  113: require("./Arc_Warden.jpeg"),
  114: require("./Monkey_King.jpeg"),
  //   115: require("./.jpeg"),
  //   116: require("./.jpeg"),
  //   117: require("./.jpeg"),
  //   118: require("./.jpeg"),
  119: require("./Dark_Willow.jpeg"),
  120: require("./Pangolier.jpeg"),
  121: require("./Grimstroke.jpeg"),
  //   122: require("./.jpeg"),
  123: require("./Hoodwink.jpeg"),
  //   124: require("./.jpeg"),
  //   125: require("./.jpeg"),
  126: require("./Void_Spirit.jpeg"),
  //   127: require("./.jpeg"),
  128: require("./Snapfire.jpeg"),
  129: require("./Mars.jpeg"),
  //   130: require("./.jpeg"),
  //   131: require("./.jpeg"),
  //   132: require("./.jpeg"),
  //   133: require("./.jpeg"),
  //   134: require("./.jpeg"),
  135: require("./Dawnbreaker.jpeg"),
  136: require("./Marci.jpeg"),
  137: require("./Primal_Beast.jpeg"),
};
export default GREYSCALE;
